### ISSUE TITLE
Mons with symbols don't work by dexno.

### ISSUE THREAD

**Issue by MattTheNub** [MegaPokeBot/MegaPokeBot#12]
Usage info
----------
* Version being used: 2.0.2
* Windows / Cmder

Issue description
-----------------
Running `%pd | 29`, `32`, `669`, or `83` seems to state "I could not find [pokemon] in my pokédex"

Steps to reproduce
------------------
1. Run `%pd | 29`, `%pd | 32`, `%pd | 669` or `%pd | 83`

Additional information
----------------------
N/A

**Comment by MattTheNub** [comment]
Also flabébé is affected (`669`)

**Comment by glacialcascade** [comment]
Note: The specified mons are Nidoran Male, Nidoran Female, and Farfetch'd.

**Comment by glacialcascade** [comment]
Fixed on a133110 (version-2 branch)
